# Generated by Django 4.2.10 on 2024-03-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlink',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
